// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace AlfaThermTaskApp.DatabaseModels
{
    public partial class Employees : DomainObject
    {
        public Employees()
        {
            WorkCard = new HashSet<WorkCard>();
        }

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string PersonalIdentityNumber { get; set; }
        public string Adress { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public int? JobId { get; set; }

        public virtual Jobs Job { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<WorkCard> WorkCard { get; set; }
    }
}