// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

#nullable disable

namespace CompanyManagmentApp.DatabaseModels
{
    public partial class Jobs : DomainObject
    {
        public Jobs()
        {
            Employees = new HashSet<Employees>();
        }

        public string JobTitle { get; set; }

        public HierarchyId DepartmentId { get; set; }
        public Departments Department { get; set; }

        public virtual ICollection<Employees> Employees { get; set; }
    }
}