// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace AlfaThermTaskApp.DatabaseModels
{
    public partial class Permission : DomainObject
    {
        public string ModuleName { get; set; }
        public bool? CanRead { get; set; }
        public bool? CanWrite { get; set; }
        public bool? CanEdit { get; set; }
        public bool? CanDelete { get; set; }
        public int? UserId { get; set; }

        public virtual Users User { get; set; }
    }
}