// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace AlfaThermTaskApp.DatabaseModels
{
    public partial class Projects : DomainObject
    {
        public Projects()
        {
            WorkCard = new HashSet<WorkCard>();
        }

        public string ProjectName { get; set; }
        public string ProjectLocation { get; set; }
        public string ProjectType { get; set; }
        public string ProjectStatus { get; set; }

        public virtual ICollection<WorkCard> WorkCard { get; set; }
    }
}