// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CompanyManagmentApp.DatabaseModels
{
    public partial class Users : DomainObject
    {
        public Users()
        {
            Permissions = new HashSet<Permission>();
        }

        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public int? EmployeeId { get; set; }

        public virtual Employees Employee { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}