// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace AlfaThermTaskApp.DatabaseModels
{
    public partial class WorkCard : DomainObject
    {
        public int? EmployeeId { get; set; }
        public int? ProjectId { get; set; }
        public DateTime? Date { get; set; }
        public int? NumberOfWorkHours { get; set; }
        public string Activities { get; set; }

        public virtual Employees Employee { get; set; }
        public virtual Projects Project { get; set; }
    }
}